### ISSUE TITLE
0.0.0.Whatever the fuck this version is. Crash on startup

### ISSUE THREAD

**Issue by SnowShock35** [AKTheKnight/AKBot#15]
The new installer doesn't do a great job at installing. Your app just crashes on startup 😛 

[Log 10-12-2016 22-27-17.txt](https://github.com/AKTheKnight/AKBot/files/644102/Log.10-12-2016.22-27-17.txt)
[Log 10-12-2016 22-27-19.txt](https://github.com/AKTheKnight/AKBot/files/644104/Log.10-12-2016.22-27-19.txt)
[Log 10-12-2016 22-27-1.txt](https://github.com/AKTheKnight/AKBot/files/644103/Log.10-12-2016.22-27-1.txt)

**Comment by AKTheKnight** [comment]
We fixed it somehow
