### ISSUE TITLE
App wont start without running it using administrator privileges 

### ISSUE THREAD

**Issue by SnowShock35** [AKTheKnight/AKBot#3]
Unable to run the app without using administrator privileges, Have no idea why. Perhaps because of unknown publisher etc.

**Comment by SnowShock35** [comment]
Tried running it in Command Prompt but no luck (Unless using admin one)

**Comment by AKTheKnight** [comment]
Yeah it will need admin privileges in order to access the data storage as it stores inside C:\Program Files. I could look at storing data somewhere else? or just having the shortcut auto use admin privileges?

**Comment by SnowShock35** [comment]
Well how to other applications get around this? They store things in C drive

**Comment by AKTheKnight** [comment]
They run as admin I'm fairly certain. Or store data elsewhere, I'll take a loook

**Comment by SnowShock35** [comment]
If u have to store elsewhere, use appdata roaming 
that's where people usually store things from what I gather. I know curse doesn't run as admin so maybe ask one of their devs
