### ISSUE TITLE
App Crashing when trying to run commands

### ISSUE THREAD

**Issue by SnowShock35** [AKTheKnight/AKBot#5]
[Log 7-12-2016 23-26-2.txt](https://github.com/AKTheKnight/AKBot/files/638046/Log.7-12-2016.23-26-2.txt)
[Log 7-12-2016 23-27-5.txt](https://github.com/AKTheKnight/AKBot/files/638047/Log.7-12-2016.23-27-5.txt)
[Log 7-12-2016 23-24-6.txt](https://github.com/AKTheKnight/AKBot/files/638048/Log.7-12-2016.23-24-6.txt)

**Comment by AKTheKnight** [comment]
Poo. My logs are useless, I don't actually include the error in the log, only the stacktrace. Todo :/

**Comment by AKTheKnight** [comment]
0.0.0.3 has a better log that should help me see the issue
